global:
  clusterConfig:
    name: ""  # name to identify this cluster for events and metrics
  sysdig:
    accessKey: ""
    accessKeySecret: ""
    region: "us1"
  image:
    registry: quay.io

agent:
  enabled: true

nodeAnalyzer:
  enabled: true

kspmCollector:
  enabled: false
